services:
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379"
      - "3000:3000"
    volumes:
      - falkordb_data:/data
    networks:
      - kg-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  kg_generator:
    build: .
    ports:
      - "8501:8501"
    environment:
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./initial_pdfs:/app/initial_pdfs
      - ./additional_pdfs:/app/additional_pdfs
    depends_on:
      falkordb:
        condition: service_healthy
    networks:
      - kg-network

networks:
  kg-network:
    driver: bridge

volumes:
  falkordb_data:
